services:
  # Application
  app:
    build:
      context: .
      dockerfile: _docker/php/Dockerfile
    working_dir: /var/www
    volumes:
      - ./:/var/www
      - ./_docker/php/php.ini:/usr/local/etc/php/conf.d/php.ini
    depends_on:
      - "database"
    networks:
      - web
      - internal
    container_name: tresksites_app
    restart: always
  # Web Server
  server:
    build:
      context: .
      dockerfile: _docker/nginx/Dockerfile
    working_dir: /var/www
    volumes:
      - ./:/var/www
      - ./_docker/nginx/vhost.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - "app"
    container_name: tresksites_server
    restart: always
    labels:
      - "traefik.http.routers.tresksites_server.rule=Host(`${PROJECT_BASE_URL}`)"
      - "traefik.port=80"
      - "traefik.docker.network=web"
    #      - "traefik.http.routers.tresksites_server.entrypoints=websecure"
    #      - "traefik.http.routers.tresksites_server.tls.certresolver=myresolver"
    networks:
      - web
      - internal
  # Database
  database:
    image: mysql:8.0
    volumes:
      - dbdata:/var/lib/mysql
    environment:
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_USER: ${DB_USER}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
    ports:
      - "33063:3306"
    container_name: tresksites_db
    restart: always
    networks:
      - internal
      - web
  # Database management
  pma:
    image: phpmyadmin:5.1
    environment:
      - PMA_ARBITRARY=1
      - PMA_HOST=${DB_HOST}
      - PMA_PORT=${DB_PORT}
    depends_on:
      - database
    ports:
      - "8887:80"
    networks:
      - web
      - internal
    container_name: tresksites_pma
    restart: always
  # Redis
  redis:
    image: redis:7.2
    container_name: tresksites_redis
    ports:
      - "6382:6379"
    networks:
      - web
      - internal
    restart: always

networks:
  web:
    external: true
  internal:
    external: false

volumes:
  dbdata:
