version: "3.9"

services:
  # Application
  app:
    build:
      dockerfile: Dockerfile
      context: .
      target: ${APP_ENV}
    labels:
      - "traefik.http.routers.tresksitesapp.rule=Host(`${APP_BASE_URL}`)"
      - "traefik.port=80"
      - "traefik.docker.network=web"
      - "traefik.http.routers.tresksitesapp.entrypoints=websecure"
      - "traefik.http.routers.tresksitesapp.tls.certresolver=myresolver"
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    env_file:
      - .env
    depends_on:
      - "database"
    networks:
      - web
      - internal
    container_name: tresksites_api_app
    restart: always
  # Database
  database:
    image: mysql:8.0
    volumes:
      - dbdata:/var/lib/mysql
    environment:
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_USER: ${DB_USER}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
    ports:
      - "3307:3306"
    container_name: tresksites_api_db
    restart: always
    networks:
      - internal
      - web
  # Database management
  pma:
    image: phpmyadmin:5.1
    environment:
      - PMA_ARBITRARY=1
      - PMA_HOST=${DB_HOST}
      - PMA_PORT=${DB_PORT}
    depends_on:
      - database
    ports:
      - "8877:80"
    networks:
      - web
      - internal
    container_name: tresksites_api_pma
    restart: always

networks:
  web:
    external: true
  internal:
    external: false

volumes:
  dbdata:
